name: CI/CD

on:
  push:
    branches:
      - ec2-docker-deploy

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image 
        run: docker build -t ntakadza/taskify .
      - name: Publish image to Docker Hub
        run: docker push ntakadza/taskify:latest

  deploy:
    needs: build-project
    runs-on: aws-ec2
    steps:
      - name: Pull image from Docker Hub
        run: docker pull ntakadza/taskify:latest
      - name: Delete Old Container 
        run: docker rm -f nextContainer || true
      - name: Run Docker Container
        run: docker run -d -p 3000:80 --name nextContainer ntakadza/taskify
       

